// <auto-generated />
using System;
using ApexGirlReportAnalyzer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApexGirlReportAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiscordServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid?>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DiscordServerId");

                    b.HasIndex("EventType");

                    b.HasIndex("UploadId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("IsActive", "ExpiresAt");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.BattleReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BattleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BattleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtractionVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BattleDate");

                    b.HasIndex("BattleType");

                    b.HasIndex("UploadId")
                        .IsUnique();

                    b.ToTable("BattleReports");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.BattleSide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveSkill")
                        .HasColumnType("integer");

                    b.Property<int>("BasicAttackBonus")
                        .HasColumnType("integer");

                    b.Property<Guid>("BattleReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dance")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraDamage")
                        .HasColumnType("integer");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer");

                    b.Property<string>("GroupTag")
                        .HasColumnType("text");

                    b.Property<string>("InGamePlayerId")
                        .HasColumnType("text");

                    b.Property<int>("InjuredCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("LossCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReduceBasicAttackDamage")
                        .HasColumnType("integer");

                    b.Property<int?>("ReinforceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RemainingCount")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Sing")
                        .HasColumnType("integer");

                    b.Property<int>("SkillBonus")
                        .HasColumnType("integer");

                    b.Property<int>("SkillReduction")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BattleReportId");

                    b.HasIndex("GroupTag");

                    b.HasIndex("Side");

                    b.HasIndex("Username");

                    b.ToTable("BattleSides");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.DiscordServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultReportPrivacy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeratorRoleIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerDiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ServerTierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscordServerId")
                        .IsUnique();

                    b.HasIndex("ServerTierId");

                    b.ToTable("DiscordServers");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.ErrorReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportedIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("UploadId");

                    b.HasIndex("UserId");

                    b.ToTable("ErrorReports");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.Tier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.TierLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyRequestLimit")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyRequestLimit")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TierId", "Scope");

                    b.ToTable("TierLimits");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.Upload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordChannelId")
                        .HasColumnType("text");

                    b.Property<string>("DiscordMessageId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiscordServerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EstimatedCostEuro")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrivacyScope")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TokenEstimate")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DiscordServerId");

                    b.HasIndex("ImageHash");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status", "CreatedAt");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InGamePlayerId")
                        .HasColumnType("text");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("TierId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.AnalyticsEvent", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.DiscordServer", "DiscordServer")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("DiscordServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Upload", "Upload")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.User", "User")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordServer");

                    b.Navigation("Upload");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.BattleReport", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Upload", "Upload")
                        .WithOne("BattleReport")
                        .HasForeignKey("ApexGirlReportAnalyzer.Models.Entities.BattleReport", "UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.BattleSide", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.BattleReport", "BattleReport")
                        .WithMany("BattleSides")
                        .HasForeignKey("BattleReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleReport");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.DiscordServer", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Tier", "Tier")
                        .WithMany("DiscordServers")
                        .HasForeignKey("ServerTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.ErrorReport", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Upload", "Upload")
                        .WithMany("ErrorReports")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.User", "User")
                        .WithMany("ErrorReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Upload");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.TierLimit", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Tier", "Tier")
                        .WithMany("TierLimits")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.Upload", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.DiscordServer", "DiscordServer")
                        .WithMany("Uploads")
                        .HasForeignKey("DiscordServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiscordServer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.User", b =>
                {
                    b.HasOne("ApexGirlReportAnalyzer.Models.Entities.Tier", "Tier")
                        .WithMany("Users")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.BattleReport", b =>
                {
                    b.Navigation("BattleSides");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.DiscordServer", b =>
                {
                    b.Navigation("AnalyticsEvents");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.Tier", b =>
                {
                    b.Navigation("DiscordServers");

                    b.Navigation("TierLimits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.Upload", b =>
                {
                    b.Navigation("AnalyticsEvents");

                    b.Navigation("BattleReport");

                    b.Navigation("ErrorReports");
                });

            modelBuilder.Entity("ApexGirlReportAnalyzer.Models.Entities.User", b =>
                {
                    b.Navigation("AnalyticsEvents");

                    b.Navigation("ErrorReports");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
